#!/usr/bin/env php
<?php
require_once dirname(__FILE__).DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR.'autoload'.DIRECTORY_SEPARATOR.'Autoload.class.php';
Autoload::register();

$CmsInstallerApp = new CmsInstallerApp($argv);
$CmsInstallerApp->init();

