#!/usr/bin/env php
<?php
define('ROOT', dirname(__FILE__).DIRECTORY_SEPARATOR);

require_once ROOT.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR.'autoload'.DIRECTORY_SEPARATOR.'Autoload.class.php';
Autoload::register();

try {
	$CmsInstallerApp = new CmsInstallerApp($argv);
	$CmsInstallerApp->init();
}
catch(Exception $e) {
	Cli::printError('Fatal error', $e->getMessage());
}
