app:
  version: 0.1
  author: 'Simon Vieille'
  contact: 'simon@deblan.fr / www.deblan.tv'
  rules:
    "version|v-s" : ~
    "list|l-s"    : ~
    "help|h-s"    : ~
    "install|i=w" : ~
    "to=w"        : ~

  configuration:
    to: {hide: true}
    version: 
      description: "Show CMS Installer version"
      param: ~
      callback:
        class: Information
        method: version

    help: 
      description: "Show help"
      param: '[command]'
      callback:
        class: Information
        method: help

    list: 
      description: "Show CMS list"
      param: '[cms]'
      callback:
        class: Information
        method: list         
      
    install:
      param: 'name [--version version] [--to destination]'
      description: "Install a CMS"
      callback:
        class: Installation
        method: install
