app:
  rules:
    version: 
      description: "Show CMS Installer version"
      callback:
        class: InformationTask
        method: version

    help: 
      description: "Show help"
      callback:
        class: InformationTask
        method: help
      
    install:
      description: "Install a CMS"
      callback:
        class: BasicTask
        method: version

