app:
  version: 0.1
  author: 'Simon Vieille'
  contact: 'simon@deblan.fr / www.deblan.tv'
  rules:
    "version|v-s"   : ~
    "help|h-s"    : ~
    "install|i=w" : ~

  configuration:
    version: 
      description: "Show CMS Installer version"
      param: ~
      callback:
        class: Information
        method: version

    help: 
      description: "Show help"
      param: '[command]'
      callback:
        class: Information
        method: help
      
    install:
      param: 'cms_name'
      description: "Install a CMS"
      callback:
        class: Installation
        method: install
