ressources:
  cms:
    wordpress:
      versions:
        default:
          callback: Wordpress
          url: http://fr.wordpress.org/latest-fr_FR.zip
        test:
          callback: Wordpress
          url: http://localhost/~simon/wp.zip
    test:
      versions:
        default:
          url: http://localhost/~simon/tar.lol

