ressources:
  cms:
    wordpress:
      versions:
        default:
          callback: Wordpress
          url: http://fr.wordpress.org/latest-fr_FR.zip
        local:
          callback: Wordpress
          url: http://localhost/~simon/wp.zip

    moncms:
      versions:
        default:
          callback: Moncms
          url: http://localhost/~simon/moncms.zip
